"use client"
import { createContext, useContext, useState, useEffect } from "react"

const T = {
  en: {
    home:"Home",venues:"Venues",bookings:"Bookings",login:"Login",profile:"Profile",logout:"Logout",signup:"Sign Up",about:"About",brand_name:"Saha Events",
    welcome:"Welcome to Saha Events",
    hero_before:"Find the ",hero_colored:"perfect",hero_after:" venue for your event",
    hero_sub:"Discover and book stunning event spaces — from intimate gatherings to grand celebrations.",
    browse:"Browse Venues",create_account:"Create Account",
    search_placeholder:"Search venues, locations...",
    all:"All",wedding:"Wedding",conference:"Conference",outdoor:"Outdoor",concert:"Concert",private_event:"Private Event",corporate:"Corporate",
    featured:"Featured Venues",view_all:"View all",
    why:"Why Choose Us",everything:"Everything you need",
    about_us:"About Us",about_desc:"Saha Events is the premier platform for discovering and booking the most exquisite venues in Algeria. We believe every event deserves a perfect setting, from intimate gatherings to grand celebrations. Our curated selection of premium spaces ensures your special moments are unforgettable. With secure booking and instant confirmation, planning your event has never been easier.",
    premium:"Premium Venues",premium_desc:"Handpicked locations for every occasion",
    secure:"Secure Booking",secure_desc:"Guaranteed reservations with full protection",
    instant:"Instant Confirmation",instant_desc:"Book now and get confirmed in minutes",
    footer_copy:"© 2026 Saha Events. Academic Project.",
    our_venues:"Our Venues",venues_sub:"Browse our curated selection of premium event spaces",
    no_venues:"No venues found.",per_day:"/ day",
    book_btn:"Book Venue",booked_btn:"✓ Booked",
    guests:"guests",capacity:"Capacity",rating:"Rating",
    view_details:"View Details",
    venue_details:"Venue Details",amenities:"Amenities",description:"Description",
    book_this_venue:"Book This Venue",select_date:"Select Date",
    event_date_label:"Event Date *",receipt_label:"CCP Payment Receipt",
    confirm_btn:"Confirm Booking",confirm_loading:"Booking...",cancel_btn:"Cancel",
    sign_in_to_book:"Sign in to book this venue",
    login_to_book:"Login or create an account to book this venue and start planning your perfect event.",
    signin_btn_cta:"Sign In",signup_btn_cta:"Create Account",
    date_taken:"Sorry, this venue is already booked for that date.",
    select_date_first:"Please select an event date.",
    upload_receipt:"Please upload your payment receipt.",
    booked_success:"Booking submitted! Pending approval.",
    my_bookings:"My Bookings",bookings_sub:"Your event reservations",
    no_bookings_title:"No bookings yet",
    no_bookings_sub:"Book your first venue and start planning something unforgettable.",
    browse_now:"Browse Venues",view_receipt:"View Receipt",
    loading:"Loading...",payment_receipt:"Payment Receipt",download_btn:"⬇ Download",
    pending:"Pending",confirmed:"Confirmed",cancelled:"Cancelled",awaiting:"Awaiting Approval",
    my_profile:"My Profile",member_since:"Member since",total_bookings:"Total Bookings",booking_history:"Booking History",
    email:"Email",password:"Password",
    sign_in:"Welcome back",sign_in_sub:"Sign in to your Saha Events account",
    signing_in:"Signing in...",no_account:"No account?",sign_up_link:"Sign up",
    sign_up:"Create account",sign_up_sub:"Join Saha Events and start booking",
    first_name:"First Name",last_name:"Last Name",creating:"Creating...",
    have_account:"Already have an account?",signin_link:"Sign in",
    password_min:"Min. 8 characters",confirm_password:"Confirm Password",repeat_password:"Repeat password",
    terms_text:"I agree to the",terms_link:"Terms",and_text:"and",privacy_link:"Privacy Policy",
    passwords_match:"✓ Match",passwords_no_match:"✗ No match",
    first_name_required:"Required",last_name_required:"Required",
    email_invalid:"Invalid email",password_short:"Min 8 chars",passwords_mismatch:"Don't match",terms_required:"Required",
    account_created:"Account created! Check your email to verify.",
    not_logged_in_bookings:"Join Saha Events",not_logged_in_sub:"Login or sign up to view your bookings and plan your perfect event.",
    admin_panel_btn:"⚙️ Admin",
    discover_venues:"Discover perfect venues",discover_venues_sub:"Explore our curated selection of premium spaces for unforgettable celebrations and events.",
    search_btn:"Search",search_venues:"Search venues, events...",
    my_bookings_title:"My Bookings",my_bookings_sub:"Manage your reservations and payments.",
    loading_dashboard:"Loading your dashboard...",loading_profile:"Loading your profile...",
    no_bookings_msg:"Book your first venue and start planning something unforgettable.",
    explore_venues:"Explore Venues",
    join_start_booking:"Join us and start booking",join_start_sub:"Sign in or create an account to book premium venues and manage your reservations.",
    view_receipt_btn:"View Receipt",no_receipt:"No receipt",
    payment_receipt_title:"Payment Receipt",download:"Download",
    da_currency:"DA",da_per_night:"DA / night",
    account_tab:"Account",receipts_tab:"Receipts",settings_tab:"Settings",
    book_a_venue:"Book a Venue",account_overview:"Here's what's happening with your bookings.",
    signin_btn:"Sign In",signup_btn:"Sign Up",
    check_email:"Check your email",sent_link:"We sent a verification link to",
    click_verify:"Click the link in the email to verify your account. Once confirmed, you'll be redirected to login automatically.",
    didnt_receive:"Didn't receive it? Check your spam folder or",try_different:"Try a different email",go_login:"Go to Login →",
    or_text:"or",
    welcome_back_msg:"Welcome back",
    account_info:"Account Info",
    role_label:"Role",
    view_all_link:"View all",
    receipts_sub:"All your payment receipts",
    no_receipts:"No receipts uploaded yet.",
    settings_heading:"Settings",
    settings_sub:"Manage your account and preferences.",
    public_info:"Public information",
    public_info_tab:"Public information",
    public_info_sub:"This will be displayed on your profile.",
    display_name:"Display name",
    username_label:"Username",
    location_label:"Location",
    location_not_set:"Location not set",
    save_changes:"Save changes",
    cancel:"Cancel",
    security:"Security",
    security_tab:"Security",
    security_sub:"Update your password and account security.",
    current_password:"Current password",
    new_password:"New password",
    confirm_new_password:"Confirm new password",
    notifications_tab:"Notifications",
    notifications:"Notifications",
    notifications_sub:"Choose what you want to hear about.",
    email_updates:"Email updates",
    email_updates_desc:"Product news and announcements.",
    booking_reminders:"Booking reminders",
    booking_reminders_desc:"Reminders 24h before your event.",
    marketing_emails:"Marketing emails",
    marketing_emails_desc:"Offers and promotions.",
    delete_account:"Delete account",
    delete_account_sub:"Permanently remove your account and data.",
    delete_btn:"Delete",
    are_you_sure:"Are you sure? This cannot be undone.",
    checking_permissions:"Checking permissions...",
    access_denied:"Access Denied",
    access_denied_sub:"You don't have admin permissions.",
    go_home:"Go Home",
    admin_title:"Admin Panel",
    platform_overview:"Overview of your platform",
    bookings_per_venue_label:"Bookings per Venue",
    total_label:"Total",
    pct_confirmed_label:"confirmed",
    add_new_venue_heading:"➕ Add New Venue",
    venue_name_label:"Venue Name",
    location_type_label:"Location / Type",
    adding:"Adding...",
    add_venue_btn:"Add Venue",
    all_venues_label:"All Venues",
    bookings_count:"bookings",
    approve_btn:"✓ Approve",
    reject_btn:"✗ Reject",
    reset_btn:"↺ Reset",
    receipt_link:"📄 Receipt",
    no_bookings_found:"No bookings found.",
    review_bookings_sub:"Review, approve or reject booking requests",
    back_to_profile:"← Back to Profile",
    navitem_account:"Account",
    navitem_receipts:"Receipts",
    navitem_settings:"Settings",
    browse_venues_link:"Explore Venues",
    no_bookings:"No bookings yet.",
    manage_venues_label:"Venues",
    manage_venues_sub_label:"Add, remove and manage venues",
    dashboard_label:"Dashboard",
    bookings_label:"Bookings",
    no_venues_msg:"No venues yet.",
    da_day:"DA/day",
    da_per_day:"/ day",
    cancel:"Cancel",
    cancel_title:"Cancel Booking",
    cancel_confirm:"Are you sure you want to cancel this booking?",
    keep:"Keep Booking",
    yes_cancel:"Yes, Cancel",
    cancelling_text:"Cancelling...",
    gender_label:"Gender",
    male:"Male",
    female:"Female",
    weak:"Weak",
    fair:"Fair",
    good:"Good",
    strong:"Strong",
    gender_required:"Please select your gender",
    password_invalid:"Password must contain letters and numbers only",
    drop_receipt:"Drop receipt or click",
    new_user_joined:"New User Joined",
    new_booking_created:"New Booking Created",
    booked_text:"booked",
    recent_activities:"Recent Activities",
    no_recent_activities:"No recent activities.",
    users_label:"Users",
    fill_all_fields:"Fill all fields and provide an image",
    error_uploading:"Error uploading image",
    delete_venue_confirm:"Delete this venue? Related bookings will be affected.",
    preferences_tab:"Preferences",
    preferences_heading:"Preferences",
    preferences_sub:"Customize your experience.",
    exit_admin:"← Exit Admin Console",
    dashboard:"Dashboard",
    dashboard_sub:"Overview of your platform's performance",
    total_users:"Total Users",
    active_venues:"Active Venues",
    no_venues_yet:"No venues added yet.",
    category_type:"Category / Type",
    price_per_day:"Price per day",
    location_ph:"e.g. Algiers, Oran",
    photo_url:"Photo URL",
    upload_photo:"📁 Upload Photo",
    paste_url:"🔗 Paste URL",
    edit:"Edit",
    pending_l:"pending",
    bookings_l:"bookings",
    total_bookings_label:"Total Bookings",
    venues_label:"Venues",
    bookings_admin_sub:"Review, approve or reject booking requests",
    admin_console: "Admin Console",
    notifications_label: "Notifications",
    no_new_notifications: "No new notifications",
    booking_approved_msg: "Your booking for {venue} has been approved!",
    booking_declined_msg: "Your booking for {venue} has been declined.",
  },
  fr: {
    home:"Accueil",venues:"Lieux",bookings:"Réservations",login:"Connexion",profile:"Profil",logout:"Déconnexion",signup:"S'inscrire",about:"À Propos",brand_name:"Saha Events",
    welcome:"Bienvenue chez Saha Events",
    hero_before:"Trouvez le lieu ",hero_colored:"parfait",hero_after:" pour votre événement",
    hero_sub:"Découvrez et réservez des espaces événementiels — des réunions intimes aux grandes célébrations.",
    browse:"Voir les lieux",create_account:"Créer un compte",
    search_placeholder:"Rechercher des lieux, des villes...",
    all:"Tout",wedding:"Mariage",conference:"Conférence",outdoor:"Extérieur",concert:"Concert",private_event:"Événement privé",corporate:"Entreprise",
    featured:"Lieux vedettes",view_all:"Voir tout",
    why:"Pourquoi nous",everything:"Tout ce qu'il vous faut",
    about_us:"À Propos De Nous",about_desc:"Saha Events est la première plateforme pour découvrir et réserver les lieux les plus exquis en Algérie. Nous croyons que chaque événement mérite un cadre parfait, des rassemblements intimes aux grandes célébrations. Notre sélection d'espaces premium garantit que vos moments spéciaux seront inoubliables. Avec une réservation sécurisée et une confirmation instantanée, l'organisation de votre événement n'a jamais été aussi simple.",
    premium:"Lieux Premium",premium_desc:"Des endroits sélectionnés pour chaque occasion",
    secure:"Réservation sécurisée",secure_desc:"Réservations garanties",
    instant:"Confirmation instantanée",instant_desc:"Réservez et confirmez en minutes",
    footer_copy:"© 2026 Saha Events. Projet Académique.",
    our_venues:"Nos Lieux",venues_sub:"Parcourez notre sélection de lieux premium",
    no_venues:"Aucun lieu trouvé.",per_day:"/ jour",
    book_btn:"Réserver",booked_btn:"✓ Réservé",
    guests:"invités",capacity:"Capacité",rating:"Note",
    view_details:"Voir détails",
    venue_details:"Détails du lieu",amenities:"Équipements",description:"Description",
    book_this_venue:"Réserver ce lieu",select_date:"Choisir la date",
    event_date_label:"Date de l'événement *",receipt_label:"Reçu de paiement CCP",
    confirm_btn:"Confirmer la réservation",confirm_loading:"Réservation...",cancel_btn:"Annuler",
    sign_in_to_book:"Connectez-vous pour réserver",
    login_to_book:"Connectez-vous ou créez un compte pour réserver ce lieu.",
    signin_btn_cta:"Se connecter",signup_btn_cta:"Créer un compte",
    date_taken:"Désolé, ce lieu est déjà réservé pour cette date.",
    select_date_first:"Veuillez sélectionner une date.",
    upload_receipt:"Veuillez télécharger votre reçu.",
    booked_success:"Réservation soumise ! En attente d'approbation.",
    my_bookings:"Mes Réservations",bookings_sub:"Vos réservations d'événements",
    no_bookings_title:"Aucune réservation",
    no_bookings_sub:"Réservez votre premier lieu et commencez à planifier quelque chose d'inoubliable.",
    browse_now:"Voir les lieux",view_receipt:"Voir le reçu",
    loading:"Chargement...",payment_receipt:"Reçu de paiement",download_btn:"⬇ Télécharger",
    pending:"En attente",confirmed:"Confirmé",cancelled:"Annulé",awaiting:"En attente d'approbation",
    my_profile:"Mon Profil",member_since:"Membre depuis",total_bookings:"Total réservations",booking_history:"Historique",
    email:"E-mail",password:"Mot de passe",
    sign_in:"Bon retour",sign_in_sub:"Connectez-vous à votre compte",
    signing_in:"Connexion...",no_account:"Pas de compte ?",sign_up_link:"S'inscrire",
    sign_up:"Créer un compte",sign_up_sub:"Rejoignez Saha Events",
    first_name:"Prénom",last_name:"Nom",creating:"Création...",
    have_account:"Déjà un compte ?",signin_link:"Se connecter",
    password_min:"Min. 8 caractères",confirm_password:"Confirmer",repeat_password:"Répéter",
    terms_text:"J'accepte les",terms_link:"Conditions",and_text:"et la",privacy_link:"Politique",
    passwords_match:"✓ Identiques",passwords_no_match:"✗ Différents",
    first_name_required:"Requis",last_name_required:"Requis",
    email_invalid:"E-mail invalide",password_short:"Min 8 chars",passwords_mismatch:"Différents",terms_required:"Requis",
    account_created:"Compte créé ! Vérifiez votre e-mail.",
    not_logged_in_bookings:"Rejoignez Saha Events",not_logged_in_sub:"Connectez-vous pour voir vos réservations.",
    admin_panel_btn:"⚙️ Admin",
    discover_venues:"Découvrez les lieux parfaits",discover_venues_sub:"Explorez notre sélection de lieux premium pour des célébrations inoubliables.",
    search_btn:"Rechercher",search_venues:"Rechercher des lieux...",
    my_bookings_title:"Mes Réservations",my_bookings_sub:"Gérez vos réservations et paiements.",
    loading_dashboard:"Chargement...",loading_profile:"Chargement du profil...",
    no_bookings_msg:"Réservez votre premier lieu et commencez à planifier.",
    explore_venues:"Explorer les lieux",
    join_start_booking:"Rejoignez-nous et réservez",join_start_sub:"Connectez-vous ou créez un compte pour réserver.",
    view_receipt_btn:"Voir le reçu",no_receipt:"Pas de reçu",
    payment_receipt_title:"Reçu de paiement",download:"Télécharger",
    da_currency:"DA",da_per_night:"DA / nuit",
    account_tab:"Compte",receipts_tab:"Reçus",settings_tab:"Paramètres",
    book_a_venue:"Réserver un lieu",account_overview:"Voici vos réservations.",
    signin_btn:"Se connecter",signup_btn:"S'inscrire",
    check_email:"Vérifiez votre e-mail",sent_link:"Nous avons envoyé un lien de vérification à",
    click_verify:"Cliquez sur le lien pour vérifier votre compte.",
    didnt_receive:"Pas reçu ? Vérifiez vos spams ou",try_different:"Essayer un autre e-mail",go_login:"Aller à la connexion →",
    or_text:"ou",
    welcome_back_msg:"Bon retour",
    account_info:"Infos du compte",
    role_label:"Rôle",
    view_all_link:"Voir tout",
    receipts_sub:"Tous vos reçus de paiement",
    no_receipts:"Aucun reçu téléchargé.",
    settings_heading:"Paramètres",
    settings_sub:"Gérez votre compte et vos préférences.",
    public_info:"Informations publiques",
    public_info_tab:"Informations publiques",
    public_info_sub:"Affiché sur votre profil.",
    display_name:"Nom affiché",
    username_label:"Nom d'utilisateur",
    location_label:"Localisation",
    location_not_set:"Localisation non définie",
    save_changes:"Enregistrer",
    cancel:"Annuler",
    security:"Sécurité",
    security_tab:"Sécurité",
    security_sub:"Mettez à jour votre mot de passe.",
    current_password:"Mot de passe actuel",
    new_password:"Nouveau mot de passe",
    confirm_new_password:"Confirmer le mot de passe",
    notifications_tab:"Notifications",
    notifications:"Notifications",
    notifications_sub:"Choisissez ce que vous voulez recevoir.",
    email_updates:"Mises à jour par e-mail",
    email_updates_desc:"Actualités et annonces produit.",
    booking_reminders:"Rappels de réservation",
    booking_reminders_desc:"Rappels 24h avant votre événement.",
    marketing_emails:"E-mails marketing",
    marketing_emails_desc:"Offres et promotions.",
    delete_account:"Supprimer le compte",
    delete_account_sub:"Supprimer définitivement votre compte.",
    delete_btn:"Supprimer",
    are_you_sure:"Êtes-vous sûr ? Cette action est irréversible.",
    checking_permissions:"Vérification des permissions...",
    access_denied:"Accès refusé",
    access_denied_sub:"Vous n'avez pas les permissions admin.",
    go_home:"Retour à l'accueil",
    admin_title:"Panneau Admin",
    platform_overview:"Vue d'ensemble de votre plateforme",
    bookings_per_venue_label:"Réservations par lieu",
    total_label:"Total",
    pct_confirmed_label:"confirmées",
    add_new_venue_heading:"➕ Ajouter un lieu",
    venue_name_label:"Nom du lieu",
    location_type_label:"Lieu / Type",
    adding:"Ajout...",
    add_venue_btn:"Ajouter",
    all_venues_label:"Tous les lieux",
    bookings_count:"réservations",
    approve_btn:"✓ Approuver",
    reject_btn:"✗ Rejeter",
    reset_btn:"↺ Réinitialiser",
    receipt_link:"📄 Reçu",
    no_bookings_found:"Aucune réservation trouvée.",
    review_bookings_sub:"Examiner, approuver ou rejeter les demandes",
    back_to_profile:"← Retour au profil",
    navitem_account:"Compte",
    navitem_receipts:"Reçus",
    navitem_settings:"Paramètres",
    browse_venues_link:"Explorer les lieux",
    no_bookings:"Aucune réservation.",
    manage_venues_label:"Lieux",
    manage_venues_sub_label:"Ajouter, supprimer et gérer les lieux",
    dashboard_label:"Tableau de bord",
    bookings_label:"Réservations",
    no_venues_msg:"Aucun lieu encore.",
    da_day:"DA/jour",
    da_per_day:"/ jour",
    cancel:"Annuler",
    cancel_title:"Annuler la réservation",
    cancel_confirm:"Voulez-vous vraiment annuler cette réservation ?",
    keep:"Garder la réservation",
    yes_cancel:"Oui, annuler",
    cancelling_text:"Annulation...",
    gender_label:"Genre",
    male:"Homme",
    female:"Femme",
    weak:"Faible",
    fair:"Moyen",
    good:"Bon",
    strong:"Fort",
    gender_required:"Veuillez sélectionner votre genre",
    password_invalid:"Le mot de passe ne doit contenir que des lettres et des chiffres",
    drop_receipt:"Déposez le reçu ou cliquez",
    new_user_joined:"Nouvel utilisateur inscrit",
    new_booking_created:"Nouvelle réservation créée",
    booked_text:"a réservé",
    recent_activities:"Activités récentes",
    no_recent_activities:"Aucune activité récente.",
    users_label:"Utilisateurs",
    fill_all_fields:"Remplissez tous les champs et fournissez une image",
    error_uploading:"Erreur lors du téléchargement de l'image",
    delete_venue_confirm:"Supprimer ce lieu ? Les réservations associées seront affectées.",
    preferences_tab:"Préférences",
    preferences_heading:"Préférences",
    preferences_sub:"Personnalisez votre expérience.",
    exit_admin:"← Quitter la console",
    dashboard:"Tableau de bord",
    dashboard_sub:"Aperçu des performances de votre plateforme",
    total_users:"Total Utilisateurs",
    active_venues:"Lieux Actifs",
    no_venues_yet:"Aucun lieu ajouté.",
    category_type:"Catégorie / Type",
    price_per_day:"Prix par jour",
    location_ph:"ex: Alger, Oran",
    photo_url:"URL de la photo",
    upload_photo:"📁 Télécharger",
    paste_url:"🔗 Coller URL",
    edit:"Modifier",
    pending_l:"en attente",
    bookings_l:"réservations",
    total_bookings_label:"Total Réservations",
    venues_label:"Lieux",
    bookings_admin_sub:"Examiner, approuver ou rejeter les demandes",
    admin_console: "Console d'administration",
    notifications_label: "Notifications",
    no_new_notifications: "Pas de nouvelles notifications",
    booking_approved_msg: "Votre réservation pour {venue} a été approuvée !",
    booking_declined_msg: "Votre réservation pour {venue} a été refusée.",
  },
  ar: {
    home:"الرئيسية",venues:"القاعات",bookings:"الحجوزات",login:"دخول",profile:"الملف الشخصي",logout:"خروج",signup:"تسجيل",about:"من نحن",brand_name:"صحا إيفنتس",
    welcome:"مرحباً بك في صحا إيفنتس",
    hero_before:"ابحث عن المكان ",hero_colored:"المثالي",hero_after:" لحدثك",
    hero_sub:"اكتشف واحجز أروع الأماكن — من التجمعات الحميمة إلى الاحتفالات الكبرى.",
    browse:"تصفح القاعات",create_account:"إنشاء حساب",
    search_placeholder:"ابحث عن القاعات والمدن...",
    all:"الكل",wedding:"زفاف",conference:"مؤتمر",outdoor:"خارجي",concert:"حفلة",private_event:"خاص",corporate:"شركات",
    featured:"قاعات مميزة",view_all:"عرض الكل",
    why:"لماذا تختارنا",everything:"كل ما تحتاجه",
    about_us:"من نحن",about_desc:"صحا إيفنتس هي المنصة الرائدة لاكتشاف وحجز أفخم القاعات في الجزائر. نحن نؤمن بأن كل مناسبة تستحق مكاناً مثالياً، من التجمعات الحميمة إلى الاحتفالات الكبرى. تضمن مجموعتنا المختارة من المساحات الفاخرة أن تكون لحظاتك الخاصة لا تُنسى. مع الحجز الآمن والتأكيد الفوري، لم يكن التخطيط لحدثك أسهل من أي وقت مضى.",
    premium:"قاعات مميزة",premium_desc:"أماكن مختارة لكل مناسبة",
    secure:"حجز آمن",secure_desc:"حجوزات مضمونة",
    instant:"تأكيد فوري",instant_desc:"احجز الآن واحصل على التأكيد",
    footer_copy:"© 2026 صحا إيفنتس. مشروع أكاديمي.",
    our_venues:"قاعاتنا",venues_sub:"تصفح مجموعتنا من القاعات الفاخرة",
    no_venues:"لا توجد قاعات.",per_day:"/ يوم",
    book_btn:"احجز",booked_btn:"✓ محجوز",
    guests:"ضيف",capacity:"السعة",rating:"التقييم",
    view_details:"عرض التفاصيل",
    venue_details:"تفاصيل القاعة",amenities:"المرافق",description:"الوصف",
    book_this_venue:"احجز هذه القاعة",select_date:"اختر التاريخ",
    event_date_label:"تاريخ الحدث *",receipt_label:"إيصال الدفع CCP",
    confirm_btn:"تأكيد الحجز",confirm_loading:"جارٍ الحجز...",cancel_btn:"إلغاء",
    sign_in_to_book:"سجّل الدخول للحجز",
    login_to_book:"سجّل الدخول أو أنشئ حساباً لحجز هذه القاعة.",
    signin_btn_cta:"تسجيل الدخول",signup_btn_cta:"إنشاء حساب",
    date_taken:"عذراً، هذه القاعة محجوزة في هذا التاريخ.",
    select_date_first:"يرجى اختيار تاريخ.",
    upload_receipt:"يرجى رفع إيصال الدفع.",
    booked_success:"تم الحجز! في انتظار الموافقة.",
    my_bookings:"حجوزاتي",bookings_sub:"حجوزات فعالياتك",
    no_bookings_title:"لا توجد حجوزات بعد",
    no_bookings_sub:"احجز قاعتك الأولى وابدأ التخطيط لحدث لا يُنسى.",
    browse_now:"تصفح القاعات",view_receipt:"عرض الإيصال",
    loading:"جارٍ التحميل...",payment_receipt:"إيصال الدفع",download_btn:"⬇ تنزيل",
    pending:"قيد الانتظار",confirmed:"مؤكد",cancelled:"ملغى",awaiting:"بانتظار الموافقة",
    my_profile:"ملفي الشخصي",member_since:"عضو منذ",total_bookings:"إجمالي الحجوزات",booking_history:"سجل الحجوزات",
    email:"البريد الإلكتروني",password:"كلمة المرور",
    sign_in:"مرحباً بعودتك",sign_in_sub:"سجّل الدخول إلى حسابك في صحا إيفنتس",
    signing_in:"جارٍ الدخول...",no_account:"ليس لديك حساب؟",sign_up_link:"إنشاء حساب",
    sign_up:"إنشاء حساب",sign_up_sub:"انضم إلى صحا إيفنتس",
    first_name:"الاسم الأول",last_name:"اللقب",creating:"جارٍ الإنشاء...",
    have_account:"لديك حساب؟",signin_link:"تسجيل الدخول",
    password_min:"٨ أحرف على الأقل",confirm_password:"تأكيد",repeat_password:"كرر",
    terms_text:"أوافق على",terms_link:"الشروط",and_text:"و",privacy_link:"الخصوصية",
    passwords_match:"✓ متطابقتان",passwords_no_match:"✗ غير متطابقتين",
    first_name_required:"مطلوب",last_name_required:"مطلوب",
    email_invalid:"بريد غير صحيح",password_short:"٨ أحرف على الأقل",passwords_mismatch:"غير متطابقتين",terms_required:"مطلوب",
    account_created:"تم إنشاء الحساب! تحقق من بريدك.",
    not_logged_in_bookings:"انضم إلى صحا إيفنتس",not_logged_in_sub:"سجّل الدخول لعرض حجوزاتك.",
    admin_panel_btn:"⚙️ الإدارة",
    discover_venues:"اكتشف القاعات المثالية",discover_venues_sub:"استكشف مجموعتنا من الأماكن الفاخرة لاحتفالات لا تُنسى.",
    search_btn:"بحث",search_venues:"ابحث عن القاعات...",
    my_bookings_title:"حجوزاتي",my_bookings_sub:"إدارة حجوزاتك ومدفوعاتك.",
    loading_dashboard:"جارٍ التحميل...",loading_profile:"جارٍ تحميل الملف...",
    no_bookings_msg:"احجز قاعتك الأولى وابدأ التخطيط لحدث لا يُنسى.",
    explore_venues:"استكشف القاعات",
    join_start_booking:"انضم إلينا وابدأ الحجز",join_start_sub:"سجّل الدخول أو أنشئ حساباً لحجز القاعات الفاخرة.",
    view_receipt_btn:"عرض الإيصال",no_receipt:"لا يوجد إيصال",
    payment_receipt_title:"إيصال الدفع",download:"تنزيل",
    da_currency:"د.ج",da_per_night:"د.ج / ليلة",
    account_tab:"الحساب",receipts_tab:"الإيصالات",settings_tab:"الإعدادات",
    book_a_venue:"احجز قاعة",account_overview:"نظرة على حجوزاتك.",
    signin_btn:"تسجيل الدخول",signup_btn:"إنشاء حساب",
    check_email:"تحقق من بريدك",sent_link:"أرسلنا رابط التحقق إلى",
    click_verify:"اضغط على الرابط للتحقق من حسابك.",
    didnt_receive:"لم تستلمه؟ تحقق من الرسائل غير المرغوبة أو",try_different:"جرب بريداً آخر",go_login:"← الذهاب لتسجيل الدخول",
    or_text:"أو",
    welcome_back_msg:"مرحباً بعودتك",
    account_info:"معلومات الحساب",
    role_label:"الدور",
    view_all_link:"عرض الكل",
    receipts_sub:"جميع إيصالات الدفع",
    no_receipts:"لا توجد إيصالات مرفوعة بعد.",
    settings_heading:"الإعدادات",
    settings_sub:"إدارة حسابك وتفضيلاتك.",
    public_info:"المعلومات العامة",
    public_info_tab:"المعلومات العامة",
    public_info_sub:"ستظهر على ملفك الشخصي.",
    display_name:"الاسم المعروض",
    username_label:"اسم المستخدم",
    location_label:"الموقع",
    location_not_set:"الموقع غير محدد",
    save_changes:"حفظ التغييرات",
    cancel:"إلغاء",
    security:"الأمان",
    security_tab:"الأمان",
    security_sub:"تحديث كلمة المرور وأمان الحساب.",
    current_password:"كلمة المرور الحالية",
    new_password:"كلمة المرور الجديدة",
    confirm_new_password:"تأكيد كلمة المرور",
    notifications_tab:"الإشعارات",
    notifications:"الإشعارات",
    notifications_sub:"اختر ما تريد تلقيه.",
    email_updates:"تحديثات البريد الإلكتروني",
    email_updates_desc:"أخبار المنتج والإعلانات.",
    booking_reminders:"تذكيرات الحجز",
    booking_reminders_desc:"تذكيرات قبل 24 ساعة من الحدث.",
    marketing_emails:"رسائل تسويقية",
    marketing_emails_desc:"العروض والترقيات.",
    delete_account:"حذف الحساب",
    delete_account_sub:"إزالة حسابك وبياناتك نهائياً.",
    delete_btn:"حذف",
    are_you_sure:"هل أنت متأكد؟ لا يمكن التراجع عن هذا.",
    checking_permissions:"جارٍ التحقق من الصلاحيات...",
    access_denied:"وصول مرفوض",
    access_denied_sub:"ليس لديك صلاحيات الإدارة.",
    go_home:"الرئيسية",
    admin_title:"لوحة الإدارة",
    platform_overview:"نظرة عامة على منصتك",
    bookings_per_venue_label:"الحجوزات لكل قاعة",
    total_label:"الإجمالي",
    pct_confirmed_label:"مؤكدة",
    add_new_venue_heading:"➕ إضافة قاعة جديدة",
    venue_name_label:"اسم القاعة",
    location_type_label:"الموقع / النوع",
    adding:"جارٍ الإضافة...",
    add_venue_btn:"إضافة",
    all_venues_label:"جميع القاعات",
    bookings_count:"حجز",
    approve_btn:"✓ موافقة",
    reject_btn:"✗ رفض",
    reset_btn:"↺ إعادة",
    receipt_link:"📄 إيصال",
    no_bookings_found:"لا توجد حجوزات.",
    review_bookings_sub:"مراجعة وقبول أو رفض طلبات الحجز",
    back_to_profile:"← العودة للملف الشخصي",
    navitem_account:"الحساب",
    navitem_receipts:"الإيصالات",
    navitem_settings:"الإعدادات",
    browse_venues_link:"استكشف القاعات",
    no_bookings:"لا توجد حجوزات بعد.",
    manage_venues_label:"القاعات",
    manage_venues_sub_label:"إضافة وحذف وإدارة القاعات",
    dashboard_label:"لوحة التحكم",
    bookings_label:"الحجوزات",
    no_venues_msg:"لا توجد قاعات بعد.",
    da_day:"د.ج/يوم",
    da_per_day:"/ يوم",
    cancel:"إلغاء",
    cancel_title:"إلغاء الحجز",
    cancel_confirm:"هل أنت متأكد من إلغاء هذا الحجز؟",
    keep:"الاحتفاظ بالحجز",
    yes_cancel:"نعم، إلغاء",
    cancelling_text:"جارٍ الإلغاء...",
    gender_label:"الجنس",
    male:"ذكر",
    female:"أنثى",
    weak:"ضعيف",
    fair:"متوسط",
    good:"جيد",
    strong:"قوي",
    gender_required:"يرجى تحديد جنسك",
    password_invalid:"يجب أن تحتوي كلمة المرور على أحرف وأرقام فقط",
    drop_receipt:"أسقط الإيصال أو انقر",
    new_user_joined:"انضم مستخدم جديد",
    new_booking_created:"تم إنشاء حجز جديد",
    booked_text:"حجز",
    recent_activities:"الأنشطة الأخيرة",
    no_recent_activities:"لا توجد أنشطة حديثة.",
    users_label:"المستخدمون",
    fill_all_fields:"يرجى ملء جميع الحقول وتقديم صورة",
    error_uploading:"حدث خطأ أثناء تحميل الصورة",
    delete_venue_confirm:"هل تريد حذف هذه القاعة؟ ستتأثر الحجوزات المرتبطة بها.",
    preferences_tab:"التفضيلات",
    preferences_heading:"التفضيلات",
    preferences_sub:"تخصيص تجربتك.",
    exit_admin:"← الخروج من لوحة الإدارة",
    dashboard:"لوحة التحكم",
    dashboard_sub:"نظرة عامة على أداء منصتك",
    total_users:"إجمالي المستخدمين",
    active_venues:"القاعات النشطة",
    no_venues_yet:"لا توجد قاعات مضافة بعد.",
    category_type:"الفئة / النوع",
    price_per_day:"السعر لليوم",
    location_ph:"مثال: الجزائر، وهران",
    photo_url:"رابط الصورة",
    upload_photo:"📁 تحميل صورة",
    paste_url:"🔗 لصق الرابط",
    edit:"تعديل",
    pending_l:"قيد الانتظار",
    bookings_l:"حجوزات",
    total_bookings_label:"إجمالي الحجوزات",
    venues_label:"القاعات",
    bookings_admin_sub:"مراجعة وقبول أو رفض طلبات الحجز",
    admin_console: "لوحة التحكم للإدارة",
    notifications_label: "الإشعارات",
    no_new_notifications: "لا توجد إشعارات جديدة",
    booking_approved_msg: "تمت الموافقة على حجزك في {venue}!",
    booking_declined_msg: "تم رفض حجزك في {venue}.",
  },
}

const ThemeContext = createContext()

export function ThemeProvider({ children }) {
  const [dark, setDark] = useState(false)
  const [lang, setLangState] = useState("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    try {
      const sl = localStorage.getItem("saha_lang")
      const sd = localStorage.getItem("saha_dark")
      if (sl && ["en","fr","ar"].includes(sl)) setLangState(sl)
      if (sd === "true") setDark(true)
    } catch(e){}
    setMounted(true)
  }, [])

  const setLang = (c) => { setLangState(c); try { localStorage.setItem("saha_lang",c) } catch(e){} }
  const toggleDark = () => setDark(d => { const n=!d; try{localStorage.setItem("saha_dark",String(n))}catch(e){}; return n })

  const t = T[lang] || T.en
  const isRTL = lang === "ar"

  const th = {
    dark, lang, isRTL, t, toggleDark, setLang,
    bg:        "transparent",
    bgCard:    dark ? "linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.01) 100%)" : "linear-gradient(135deg, rgba(255,255,255,0.6) 0%, rgba(255,255,255,0.2) 100%)",
    bgNav:     dark ? "linear-gradient(135deg, rgba(24,21,15,0.7) 0%, rgba(24,21,15,0.3) 100%)" : "linear-gradient(135deg, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0.4) 100%)",
    border:    dark ? "rgba(255,255,255,0.12)" : "rgba(255,255,255,0.6)",
    text:      dark ? "#f0ebe4" : "#1e1a16",
    textMuted: dark ? "#9e9088" : "#8a7d72",
    accent:    "#c9a84c",
    accentGlow:"rgba(201,168,76,0.22)",
    accentStrong:"rgba(201,168,76,0.38)",
    surface:   dark ? "rgba(255,255,255,0.03)" : "rgba(255,255,255,0.5)",
    pending:   "#d97706",
    confirmed: "#16a34a",
    cancelled: "#dc2626",
    glassCard: dark ? "linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.01) 100%)" : "linear-gradient(135deg, rgba(255,255,255,0.6) 0%, rgba(255,255,255,0.2) 100%)",
    glassBorder: dark ? "rgba(255,255,255,0.12)" : "rgba(255,255,255,0.6)",
    glassFilter: "blur(28px) saturate(180%)",
    cardShadow: dark
      ? "0 12px 40px rgba(0,0,0,0.4), 0 1px 1px rgba(255,255,255,0.15) inset, 0 -1px 1px rgba(0,0,0,0.4) inset"
      : "0 12px 40px rgba(0,0,0,0.08), 0 1px 1px rgba(255,255,255,0.9) inset, 0 -1px 1px rgba(255,255,255,0.3) inset",
    hoverShadow: dark
      ? "0 24px 64px rgba(0,0,0,0.5), 0 0 0 1px rgba(201,168,76,0.25)"
      : "0 24px 64px rgba(0,0,0,0.15), 0 0 0 1px rgba(201,168,76,0.25)",
  }

  if (!mounted) return null

  return (
    <ThemeContext.Provider value={th}>
      <div dir={isRTL?"rtl":"ltr"} className={dark ? "dark" : ""} style={{
        background: "transparent", color: th.text, minHeight: "100vh",
        transition: "color 0.35s",
        fontFamily: isRTL ? "'IBM Plex Sans Arabic', 'El Messiri', 'Alexandria', sans-serif" : "'DM Sans', sans-serif",
      }}>
        {children}
      </div>
    </ThemeContext.Provider>
  )
}

export const useTheme = () => useContext(ThemeContext)